#!/bin/bash

echo update
apt-get update
apt-get -y upgrade

echo install prerequisites
apt-get install -y autoconf gcc libc6 make wget unzip apache2 apache2-utils php libgd-dev openssl libssl-dev

echo download nagios
cd /tmp
wget --no-check-certificate -O nagioscore.tar.gz https://github.com/NagiosEnterprises/nagioscore/archive/refs/tags/nagios-4.5.1.tar.gz
tar xzf nagioscore.tar.gz

echo compile nagios
cd /tmp/nagioscore-nagios-4.5.1/
./configure --with-httpd-conf=/etc/apache2/sites-enabled
make all

echo create user and group
make install-groups-users
usermod -a -G nagios www-data

echo install binaries
make install

echo install service
make install-daemoninit

echo install command mode
make install-commandmode

echo install configuration files
make install-config

echo install apache configuration files
make install-webconf
a2enmod rewrite
a2enmod cgi

echo create nagiosadmin user account
htpasswd -b -c /usr/local/nagios/etc/htpasswd.users nagiosadmin nagios

echo restart apache
systemctl restart apache2.service

echo start nagios
systemctl start nagios.service

echo install nagios plugins prerequisites
apt-get install -y autoconf gcc libc6 libmcrypt-dev make libssl-dev wget bc gawk dc build-essential snmp libnet-snmp-perl gettext

echo download nagios plugins
cd /tmp
wget --no-check-certificate -O nagios-plugins.tar.gz https://codeload.github.com/nagios-plugins/nagios-plugins/tar.gz/refs/tags/release-2.4.9
tar zxf nagios-plugins.tar.gz

echo install nagios plugins
cd /tmp/nagios-plugins-release-2.4.9/
./tools/setup
./configure
make
make install

echo restart apache
systemctl restart apache2.service

echo restart nagios
systemctl restart nagios.service

echo ===========================================
echo nagios installation has been completed
echo access it using http://$(hostname -I | cut -d' ' -f1)/nagios
echo username: nagiosadmin
echo password: nagios
echo ===========================================
